# Generated by Django 4.2 on 2023-08-07 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phone_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.TextField(max_length=255, verbose_name='その他の要望')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='投稿日')),
                ('phone_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'other_requests',
            },
        ),
    ]
