# Generated by Django 4.2 on 2023-10-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('notice', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulletin',
            },
        ),
        migrations.CreateModel(
            name='Bulletin_middle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminer.bulletin', verbose_name='投稿内容')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.shelter', verbose_name='避難所選択')),
            ],
            options={
                'db_table': 'bulletin_middle',
            },
        ),
    ]
