# Generated by Django 4.2 on 2023-07-04 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='p_support_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='物資一覧')),
                ('quantity', models.IntegerField(verbose_name='個数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申請日')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='到着予定日')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'p_support_Item',
            },
        ),
    ]
