# Generated by Django 4.2.3 on 2024-03-11 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phone", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="biginner_account_and_Other_requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="名前")),
                ("requests", models.TextField(max_length=255, verbose_name="その他の要望")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日時"
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.shelter",
                        verbose_name="避難所選択",
                    ),
                ),
            ],
            options={
                "verbose_name": "[情報弱者その他の要望]",
                "verbose_name_plural": "情報弱者その他の要望一覧",
                "db_table": "biginner_account_and_Other_requests",
            },
        ),
        migrations.CreateModel(
            name="beginner_account_and_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="名前")),
                ("gender", models.CharField(max_length=128, verbose_name="性別")),
                ("birthdate", models.DateField(verbose_name="生年月日")),
                ("item_name", models.CharField(max_length=255, verbose_name="物資一覧")),
                ("quantity", models.IntegerField(verbose_name="個数")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日時"
                    ),
                ),
                (
                    "arrival_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="到着予定日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.shelter",
                        verbose_name="避難所選択",
                    ),
                ),
            ],
            options={
                "verbose_name": "[情報弱者支援物資]",
                "verbose_name_plural": "情報弱者支援物資要請一覧",
                "db_table": "beginner_account_and_item",
            },
        ),
    ]
