# Generated by Django 4.2.3 on 2024-07-12 03:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="other_requests",
            options={
                "verbose_name": "other_requests",
                "verbose_name_plural": "other_requests",
            },
        ),
        migrations.AlterModelOptions(
            name="p_support_item",
            options={
                "verbose_name": "[支援物資]",
                "verbose_name_plural": "Request for Relief Supplies",
            },
        ),
        migrations.AlterModelOptions(
            name="shelter",
            options={"verbose_name": "Evacuation", "verbose_name_plural": "Evacuation"},
        ),
        migrations.AlterField(
            model_name="account",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女"), ("未回答", "未回答")],
                max_length=128,
                verbose_name="sex",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="other_requests",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="application date",
            ),
        ),
        migrations.AlterField(
            model_name="p_support_item",
            name="arrival_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated arrival date"
            ),
        ),
        migrations.AlterField(
            model_name="p_support_item",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="application date",
            ),
        ),
        migrations.AlterField(
            model_name="p_support_item",
            name="item_name",
            field=models.CharField(max_length=255, verbose_name="item_name"),
        ),
        migrations.AlterField(
            model_name="p_support_item",
            name="quantity",
            field=models.IntegerField(verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="shelter_name",
            field=models.CharField(max_length=30, verbose_name="Evacuation_name"),
        ),
    ]
