# Generated by Django 4.2.3 on 2024-07-12 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_alter_other_requests_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="age",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女"), ("未回答", "未回答")],
                max_length=128,
                verbose_name="gender",
            ),
        ),
    ]
