# Generated by Django 4.2 on 2023-09-13 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biginner_account_and_Other_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='名前')),
                ('gender', models.TextField(choices=[('男', '男'), ('女', '女'), ('未回答', '未回答')], verbose_name='性別')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='年齢')),
                ('requests', models.TextField(max_length=255, verbose_name='その他の要望')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shelter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phone.shelter', verbose_name='避難所選択')),
            ],
            options={
                'db_table': 'biginner_account_and_Other_requests',
            },
        ),
        migrations.CreateModel(
            name='beginner_account_and_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='名前')),
                ('gender', models.TextField(choices=[('男', '男'), ('女', '女'), ('未回答', '未回答')], verbose_name='性別')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='年齢')),
                ('item_name', models.CharField(max_length=255, verbose_name='物資一覧')),
                ('quantity', models.IntegerField(verbose_name='個数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='到着予定日')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phone.shelter', verbose_name='避難所選択')),
            ],
            options={
                'db_table': 'beginner_account_and_item',
            },
        ),
    ]
